export const FETCH_GLOBAL_CASES_REQUEST = "FETCH_GLOBAL_CASES_REQUEST";
export const FETCH_GLOBAL_CASES_SUCCESS = "FETCH_GLOBAL_CASES_SUCCESS";
export const FETCH_GLOBAL_CASES_ERROR = "FETCH_GLOBAL_CASES_ERROR";

export const FETCH_COUNTRY_CASES_REQUEST = "FETCH_COUNTRY_CASES_REQUEST";
export const FETCH_COUNTRY_CASES_SUCCESS = "FETCH_COUNTRY_CASES_SUCCESS";
export const FETCH_COUNTRY_CASES_ERROR = "FETCH_COUNTRY_CASES_ERROR";
